#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

export PATH:$PATH:~/.ghcup/bin:~/.local/bin/
# start some nice programs
exec nitrogen --restore &
exec clipmenud &
exec picom &
exec lightscreen -i &

outputs=$(xrandr --query | grep " connected" | cut -d" " -f1)
tray_output=eDP1

for m in $outputs; do
  if [[ $m == "DVI-D-1" ]]; then
      tray_output=$m
  fi
done

for m in $outputs; do
  export MONITOR=$m
  if [[ $m =~ ([a-zA-Z]+) ]]; then export MONIT=$BASH_REMATCH; fi
  export TRAY_POSITION=none
  if [[ $m == $tray_output ]]; then
    TRAY_POSITION=right
  fi
  exec polybar bar & 
done

exec xmonad 
