#! /bin/sh

devilspie &
bash ~/.config/polybar/launch.sh --cuts &
feh --bg-scale ~/Images/7.jpg &
lightscreen -i &
dunst &
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc_bspwm &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xcompmgr -c &
